name: condor_sports_flutter
description: Fluter version of Condor Sports

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # Service locator
  get_it: ^4.0.1
  # Bloc for state management
  flutter_bloc: ^3.2.0
  # Value equality
  equatable: ^1.1.1
  # Functional programming thingies
  dartz: ^0.8.9
  # Remote API
  data_connection_checker: ^0.3.4
  http: ^0.12.0+4
  # Local cache
  shared_preferences: ^0.5.7
  # Data class representation
  freezed_annotation: 0.7.1
  # Json Serializable
  json_serializable: 3.3.0
  # SVG Loader
  flutter_svg: ^0.17.4
  # Speed Dial FB
  flutter_speed_dial: 1.2.5
  # Internationalization
  intl: 0.16.1
  # URL Launcher
  url_launcher: 5.4.5

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^4.1.1
  build_runner:
  freezed: 0.10.4

flutter:
  assets:
    - images/ic_la_liga.png
    - images/ic_english.png
    - images/ic_russian_league.png
    - images/ic_replace.svg
    - images/ic_facebook.svg
    - images/ic_website.svg
    - images/ic_twitter.svg
    - images/ic_instagram.svg
    - images/ic_youtube.svg
    - images/ic_no_img.svg
    - images/ic_soccer_ball.svg

  uses-material-design: true
